// <auto-generated />
using System;
using DKCN.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DKCN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221028100322_UpdateDBContext")]
    partial class UpdateDBContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DKCN.Models.ThongTinKhac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAILSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GIOITINH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEDAOTAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOTEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KHOA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KHOAHOC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LYDO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NGANHHOC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NGAYDANGKI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAYSINH")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("XACNHAN")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("ThongTinKhac");
                });

            modelBuilder.Entity("DKCN.Models.ThongTinVayVon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAILSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GIOITINH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEDAOTAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOTEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KHOA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KHOAHOC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LYDO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NGANHHOC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NGAYCAP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAYDANGKI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAYNHAPHOC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAYSINH")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOICAP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("THOIGIANRATRUONG")
                        .HasColumnType("datetime2");

                    b.Property<string>("THUOCDIEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THUOCDOITUONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("XACNHAN")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("ThongTinVayVon");
                });
#pragma warning restore 612, 618
        }
    }
}
